import java.awt.Color;
import java.awt.image.BufferedImage;

/**
 * 
 * Handles loading and sorting map items
 * 
 * @author Joss
 *
 */
public class Map {

	// Constants
	public static final int CLEAR = new Color(0, 0, 0, 0).getRGB();
	
	public static final int SPRITE_MEGA = 1,
							SPRITE_PILL = 2,
							
							PATH_MOVE = 1,
							PATH_CROSS = 2,
							PATH_SPECIAL = 3,
							
							SPRITE_TEX = 9;

	// Members
	private int m_spriteCount, m_startX, m_startY, m_enemyX, m_enemyY;

	/**
	 * Constructor
	 * 
	 * @param wallID
	 *            The walls map
	 * @param spriteID
	 *            The sprite map
	 * @param pathID
	 *            The paths map
	 */
	public Map() {
		// Enemy block at: 13,11
		m_enemyX = 13;
		m_enemyY = 11;
		
		// Start block at: 14,23
		m_startX = 23;
		m_startY = 14;
		
		m_sprite_map = new int[SPRITE_MAP.length][SPRITE_MAP[0].length];
		
		resetSprites();
	}
	
	/**
	 * Counts the number of sprites and randomizes pills
	 */
	private void sortSprites() {
		for (int x = 0; x < m_sprite_map.length; x++) {
			for (int y = 0; y < m_sprite_map[0].length; y++) {
				if (m_sprite_map[x][y] >= SPRITE_PILL) {
					m_spriteCount++;
					m_sprite_map[x][y] = SPRITE_PILL + (int)(Math.floor(Math.random() * SPRITE_TEX));
				}
			}
		}
	}
	
	public void resetSprites() {
		for (int x = 0; x < m_sprite_map.length; x++) {
			for (int y = 0; y < m_sprite_map[0].length; y++) {
				m_sprite_map[x][y] = SPRITE_MAP[x][y];
			}
		}
		
		sortSprites();
	}

	/**
	 * Gets the number of sprites
	 * 
	 * @return The count
	 */
	public int getSpriteCount() {
		return m_spriteCount;
	}
	
	/**
	 * Gets the start x
	 * 
	 * @return The x coord
	 */
	public int getStartX() {
		return m_startX;
	}

	/**
	 * Gets the start y
	 * 
	 * @return The y coord
	 */
	public int getStartY() {
		return m_startY;
	}
	
	/**
	 * Gets the enemy x
	 * 
	 * @return The x coord
	 */
	public int getEnemyX() {
		return m_enemyX;
	}

	/**
	 * Gets the enemy y
	 * 
	 * @return The y coord
	 */
	public int getEnemyY() {
		return m_enemyY;
	}
	
	public static Color[] BLOCK_COLOUR = {
		new Color(0,0,0),
		new Color(0,0,0),
		new Color(51,51,51),
		new Color(153,153,153),
		new Color(153,153,153),
		new Color(0,128,64),
		new Color(255,0,128)
	};
	
	public int[][] m_sprite_map = null;
	private static final int[][] SPRITE_MAP = {
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,2,2,2,2,2,2,2,2,2,2,2,2,0,0,2,2,2,2,2,2,2,2,2,2,2,2,0},
		{0,2,0,0,0,0,2,0,0,0,0,0,2,0,0,2,0,0,0,0,0,2,0,0,0,0,2,0},
		{0,1,0,0,0,0,2,0,0,0,0,0,2,0,0,2,0,0,0,0,0,2,0,0,0,0,1,0},
		{0,2,0,0,0,0,2,0,0,0,0,0,2,0,0,2,0,0,0,0,0,2,0,0,0,0,2,0},
		{0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0},
		{0,2,0,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,2,0,0,2,0,0,0,0,2,0},
		{0,2,0,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,2,0,0,2,0,0,0,0,2,0},
		{0,2,2,2,2,2,2,0,0,2,2,2,2,0,0,2,2,2,2,0,0,2,2,2,2,2,2,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0},
		{0,2,2,2,2,2,2,2,2,2,2,2,2,0,0,2,2,2,2,2,2,2,2,2,2,2,2,0},
		{0,2,0,0,0,0,2,0,0,0,0,0,2,0,0,2,0,0,0,0,0,2,0,0,0,0,2,0},
		{0,2,0,0,0,0,2,0,0,0,0,0,2,0,0,2,0,0,0,0,0,2,0,0,0,0,2,0},
		{0,1,2,2,0,0,2,2,2,2,2,2,2,0,0,2,2,2,2,2,2,2,0,0,2,2,1,0},
		{0,0,0,2,0,0,2,0,0,2,0,0,0,0,0,0,0,0,2,0,0,2,0,0,2,0,0,0},
		{0,0,0,2,0,0,2,0,0,2,0,0,0,0,0,0,0,0,2,0,0,2,0,0,2,0,0,0},
		{0,2,2,2,2,2,2,0,0,2,2,2,2,0,0,2,2,2,2,0,0,2,2,2,2,2,2,0},
		{0,2,0,0,0,0,0,0,0,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,0,0,2,0},
		{0,2,0,0,0,0,0,0,0,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,0,0,2,0},
		{0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
	};
	
	public int[][] m_path_map = {
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
		{0,1,1,1,1,1,2,1,1,1,1,1,1,0,0,1,1,1,1,1,1,2,1,1,1,1,1,0},
		{0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0},
		{0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0},
		{0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0},
		{0,2,1,1,1,1,2,1,1,2,1,1,2,1,1,2,1,1,2,1,1,2,1,1,1,1,2,0},
		{0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0},
		{0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0},
		{0,1,1,1,1,1,2,0,0,1,1,1,1,0,0,1,1,1,1,0,0,2,1,1,1,1,1,0},
		{0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,1,1,1,3,1,1,3,1,1,1,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,2,1,1,2,0,0,0,0,0,0,0,0,2,1,1,2,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,2,1,1,1,1,1,1,1,1,2,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0},
		{0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0},
		{0,1,1,1,1,1,2,1,1,2,1,1,1,0,0,1,1,1,2,1,1,2,1,1,1,1,1,0},
		{0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0},
		{0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0},
		{0,1,1,1,0,0,2,1,1,2,1,1,3,1,1,3,1,1,2,1,1,2,0,0,1,1,1,0},
		{0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0},
		{0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0},
		{0,1,1,2,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,2,1,1,0},
		{0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0},
		{0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0},
		{0,1,1,1,1,1,1,1,1,1,1,1,2,1,1,2,1,1,1,1,1,1,1,1,1,1,1,0},
		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
	};
	
	public Block[][] m_map = {
			{
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER)
			},
			{
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null
			},
			{
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null
			},
			{
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_GATE),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null
			},
			{
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER)
			},
			{
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null
			},
			{
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null
			},
			{
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null
			},
			{
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				new Block(Wall.TEX_BLUE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				new Block(Wall.TEX_ORANGE),
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				new Block(Wall.TEX_OUTER)
			},
			{
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER),
				new Block(Wall.TEX_OUTER)
			}
		};

}
